### ISSUE TITLE
Eclectic-Tech http://wxdata.weather.com/ import no longer working

### ISSUE THREAD

**Issue by MoRbIdBoY** [MinhThienDX/win10widgets#15]
Weather (ExtraLarge).ini

http://wxdata.weather.com
This service is deprecated as of 01/15/2020

Apparently it did the same thing back in October, 2019 and come back up, so who knows.

**Comment by MinhThienDX** [comment]
Thank you for reporting.
The author Eclectic-Tech already notice this problem.
See his comment here https://www.deviantart.com/eclectic-tech/art/Win10-Weather-Patch-V2-0-1-780236969

**Comment by MoRbIdBoY** [comment]
Thanks for the heads up, I'll keep a check on progress :)
