### ISSUE TITLE
Weather widget does not auto-refresh

### ISSUE THREAD

**Issue by BudSpencer20** [MinhThienDX/win10widgets#18]
Hey MinhThienDX,

Firstly great work on reviving this fantastic Rainmeter skin!

It would seem that the Weather widget does not auto-refresh meaning it always displays weather from when Rainmeter first started up - you have to manually refresh it to get the latest weather.

I believe the original version of the Weather widget did this.

Thanks very much :)

**Comment by MinhThienDX** [comment]
Can you try this? https://www.deviantart.com/eclectic-tech/art/Win10-Weather-Patch-V2-0-1-780236969

**Comment by throttlemeister** [comment]
Same issue, but I haven't been able to register to Deviantart for months and as such cannot download to try this possible fix.

**Comment by MinhThienDX** [comment]
@throttlemeister Just use the latest version of this repo, you don't need to go to Deviantart.

**Comment by throttlemeister** [comment]
@MinhThienDX Thanks for the heads-up, didn't see you had already updated. Very much appreciated you maintaining a fork of this now that the original is essentially abandoned.

**Comment by MinhThienDX** [comment]
@throttlemeister Yeah I got a lot of help from other folks too.
