### ISSUE TITLE
GPU widet goes over 100%

### ISSUE THREAD

**Issue by tipek360** [MinhThienDX/win10widgets#20]
Hey,
i found another bug in your for of win10widgets and that is that percentage counter for GPU can go over 100%

![image](https://user-images.githubusercontent.com/29817294/77166099-e90f3680-6ab3-11ea-8754-d831ee32a7cb.png)

**Comment by MinhThienDX** [comment]
Weird, can you post the Task Manager's Performance tab when that happen?

**Comment by tipek360** [comment]
OK Here is my screen from task manager's performance tab
![image](https://user-images.githubusercontent.com/29817294/77408844-9e920080-6db8-11ea-9c5b-9990c652960c.png)

And it looks like that GPU widget makes total of all percentage values shown in GPU of task manager.

**Comment by MinhThienDX** [comment]
PR #21 has been merged, you can try to use it with MSI Afterburner or HWiNFO
If you don't want to use those tools, can you try below setting?
https://forum.rainmeter.net/viewtopic.php?t=28813

**Comment by tipek360** [comment]
So I solved my issue using Afterburner but to make it working I had to comment UssageMonitor condition.

**Comment by Kablion** [comment]
#23 should fix this.
