### ISSUE TITLE
Feature Request: Hard Drives Perf Combo widget

### ISSUE THREAD

**Issue by Tromador** [MinhThienDX/win10widgets#24]
I would dearly love to see a widget which shows the performance of multiple disks in one box the size of a small "Performance - Disk". 

I have tried and to my shame I cannot get my head around how these widgets work, so the best I've managed is to get a separate "Performance - Disk2" which is fine, but uses up more desktop space than I would like. 

I've been into disk Template.ini; disk Selector.ini; tried making my own combo.ini, performance TemplateX2.ini; and I just get lost as one thing refers to another and another. I'm lost, perhaps you guys can do better than me.

**Comment by MinhThienDX** [comment]
> multiple disks in one box the size of a small "Performance - Disk"
> so the best I've managed is to get a separate "Performance - Disk2" which is fine, but uses up more desktop space than I would like

Can you use Tiny size with multiple Performance - Disk copy to reduce desktop space?
There is really no magic to put multiple disk in one skin, it can be done.
However, that will make that skin cluttered and when compared to other element, it is not consistent.
With multiple Performance - Disk, you can also arrange widget in whatever combination you see fit.
