### ISSUE TITLE
"Error: Spotify Plugin not working" instead of artist/song title

### ISSUE THREAD

**Issue by Shushuda** [MinhThienDX/win10widgets#26]
Hi, I'm having a problem with setting up the Spotify widget and cannot seem to fix it. Perhaps I am doing something wrong - I'd rather ask here in case it's a real bug and not my fault.

I've installed Spicetify (to get the .dll) and added manually WebNowPlaying .dll file to the plugin dir. I've loaded the Spotify widget (smallest version) and it's correctly controlling the play/pause, next and previous buttons (I can use those fine to control Spotify), but their images are not changing (not sure if the play should change to a pause image when the song is playing) and the artist and song title is nowhere to be seen - instead, I get "Error: Spotify Plugin not working" in their place. Timestamps and covers are also not displayed at all.

![sadasdasda](https://user-images.githubusercontent.com/26089938/82100562-3998be00-970a-11ea-9780-96c51b8ab5cd.png)

**Comment by InterFelix** [comment]
This means that the skin has no connection to Spotify via WebNowPlaying. Have you successfully installed spicetify using spicetify-cli?

**Comment by MinhThienDX** [comment]
@InterFelix I see your PR at  tjmarkham/win10widgets, but that repo is abandoned.
If you make a PR here, I will merge it.

**Comment by InterFelix** [comment]
Will do once I am back at my desk. Probably in an hour or so. I'm very interested in bringing this project forward, but I'm new to rainmeter.

**Comment by MinhThienDX** [comment]
@InterFelix No rush, this is an open source project, you can participate at your own pace whenever you want.
Don't worry about being new, there is always a first time for everything 😉

**Comment by InterFelix** [comment]
Okay. I'm trying to integrate my changes into the existing, tweaked spotify widget, but I now have a similar problem to the one @Shushuda has. No cover displayed, no Track/Artist-names, controls work, but play/pause changes and also the progress bar works. However, also no Duration and progress in minutes. 
So I undid all my changes (fetch origin, so all files are fresh from the repo) and the problem persisted.
I think I'm going to replace all your measures with mine, so it can work more reliably. I basically adapted them from another Skin calles SpotifyControl by fuckyeahlucas, which works all the time (I have it open for comparison).

**Comment by InterFelix** [comment]
My PR should fix this issue. We should add a release for this, so @Shushuda can easily download the new version.

**Comment by MinhThienDX** [comment]
@InterFelix Done.
@Shushuda You can check the plugin and then close this issue.

**Comment by InterFelix** [comment]
Thanks a lot. However, I think we need a new release, since the last one is from 2016. @MinhThienDX , can you create a new one? I have already built an .rmskin file, but you can do so yourself if you prefer.

**Comment by MinhThienDX** [comment]
Actually I am against the release of rmskin file.

For a few reason below:
1. It take time and effort for insignificant gain since rmskin file is just a modified zip file
2. To update a skin, git pull is much faster and easier than using rmskin file (even download as zip from GitHub is better as the author don't have to create zip file)
3. Rainmeter users probably are tech-savvy enough to get by without rmskin

All that time and effort can be used to actually improve the skin instead 😉
And don't worry, we don't need a new release because no one have never asked about rmskin file.
You are the first to mention it 😂
Think of this repo is the latest release without builtin auto update but the users can easily "add" auto update "feature" with git 😉

**Comment by InterFelix** [comment]
Okay, fair enough. But, you know, it's very easy to do using the built-in feature in Rainmeter. 
However, your choice, so do what you think is right. I of course use git for this, but the majority of skins is released in .rmskin form, because everyone can install an .rmskin file, while maybe not everyone can git pull. But whatever, fair point. Most people that care enought about their desktop to use Rainmeter can wrap their head around basic git ;-)

**Comment by MinhThienDX** [comment]
I deleted the v1.0.0 tag, it is not even a rmskin file 😂

**Comment by InterFelix** [comment]
Yes, that's right. Maybe best to do so

**Comment by InterFelix** [comment]
However, I don't really know how I should efficiently use git for updating. My skins folder has more than just win10widgets in it, of course. And if I clone into a subdirectory, the widgets break for whatever reason...

**Comment by MinhThienDX** [comment]
![Untitled](https://user-images.githubusercontent.com/13492015/82913982-2ce15900-9f99-11ea-96fd-c7963d836aea.png)
You can make it like so

1. Clone the repo some where
2. Move .git folder (**hidden**) and everything else to Documents/Rainmeter/Skins
That's it.

**Comment by InterFelix** [comment]
Yeah, okay. Since I can't directly commit I don't need .gitignore anyways

**Comment by MinhThienDX** [comment]
Just use your fork and you can direct commit or do whatever your heart desire 😉
You can put secret/personal stuff in another branch and public stuff in master branch.
That way you can easily create PR.

**Comment by InterFelix** [comment]
Yeah, of course. I'll just look around and fix whatever I come across (if I manage to do so)

**Comment by MinhThienDX** [comment]
Thank you in advance.
However, I don't ask/expect you to fix all the issue.
Just fix what affect you and give back to the community if you want.
Give and take, don't use too much of your personal time to give stuff for others to use.
Take care of yourself first.

**Comment by Shushuda** [comment]
Hi, sorry for the long absence. I've downloaded the newer version after the fix got merged and the Spotify widget is working perfectly fine now. Thank you for your help! I will close the issue now.

**Comment by InterFelix** [comment]
Do you see covers? After the latest Spotify update there are no covers display anymore (for me at least)

**Comment by MinhThienDX** [comment]
Look like we are not alone https://www.deviantart.com/cybergen49/art/SpotiPlayer-for-Rainmeter-813654412
