### ISSUE TITLE
Sync dark/light theme with Windows 10

### ISSUE THREAD

**Issue by xmha97** [MinhThienDX/win10widgets#30]
The latest version of windows has a dark theme, which changes elements such as context menus to be dark, so if I schedule windows to change to the dark theme automatically at night, it wouldn't affect [win10widgets](https://github.com/MinhThienDX/win10widgets), because all elements are skinned.​

![image](https://user-images.githubusercontent.com/23485114/83338673-e747c780-a2db-11ea-841d-b1e74a9b0b4b.png)

**Comment by xmha97** [comment]
The configuration can be queried in the registry's following location:
* Key: `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize`
* Value: `AppsUseLightTheme`

When the value equals 0 (DWORD), it means it is in dark mode. Altering the value triggers immediately Windows Explorer to go/exit dark mode.
Some resources:
* https://stackoverflow.com/questions/53501268/win10-dark-theme-how-to-use-in-winapi
* https://github.com/ysc3839/win32-darkmode
* [microsoft/terminal#277 (comment)](https://github.com/microsoft/terminal/issues/277#issuecomment-428831635)

**Comment by MinhThienDX** [comment]
Thank you for this discovery.
If you can create a pull request to integrate the detection of this registry value into win10widgets, I will merge into this repo as soon as possible.

**Comment by MinhThienDX** [comment]
@xmha97 There is light mode of this skin, please take a look at it.

**Comment by xmha97** [comment]
Thanks for supporting the dark theme.
But I want the widget theme to be synced with the Windows theme.
That is, when Windows is light, the widget is also light.
And when Windows is dark, so is the widget.
Reopen this issue if its implementation is possible.

**Comment by xmha97** [comment]
cc: @MinhThienDX

**Comment by MinhThienDX** [comment]
Sorry but currently I don't have the time to do so 😥
