### ISSUE TITLE
Support for Windows Store Spotify

### ISSUE THREAD

**Issue by DoyleElv** [MinhThienDX/win10widgets#31]
Hi, I'm having a problem with the Spotify widget. The widget doesn't work whenever I open the app or play a song/playlist. It just does nothing, no error displayed. I believe this problem happens because the Spotify app which I use is from Windows Store (even though it's an official win32 app, not PWA or UWP).
![image](https://user-images.githubusercontent.com/66320309/83537382-ae4b6500-a51e-11ea-9cef-a4fe7fcccb71.png)
Image Description: I'm playing Fire on fire by Sam Smith on Spotify but the widget shows nothing!

So, is it because the app comes from Windows Store, or is it something else that make this issue? If the problem is because of the Store, may you add support? It's no rush but it's nice to see this issue get fixed ;)

**Comment by MinhThienDX** [comment]
Can you try with Spotify client? (the stuff not from Windows Store)

**Comment by DoyleElv** [comment]
I haven't tried it. But guess I'll have to uninstall the Windows Store version of the app first as both versions are maybe the same.

**Comment by DoyleElv** [comment]
The wigdet doesn't work with the version that I download from web either :(

**Comment by DoyleElv** [comment]
Hmm so that's nothing we can do (yet), then X'D
Btw, can you add Fluent Design (or in particular, the frosted glass Acrylic) to the skin? 🥺

**Comment by MinhThienDX** [comment]
Can you include a picture to showcase that?

**Comment by DoyleElv** [comment]
Since Fall Creators Update 2017 of Windows 10, Microsoft have upgraded their Modern UI to Fluent Design System. You can read more about it here: https://en.wikipedia.org/wiki/Fluent_Design_System
https://www.microsoft.com/design/fluent/#/

I don't think I can explain this Acrylic thing well ._. Like instead of merely transculent, the interface includes frost foggy thing or whatever it is called, that blurs the background yet still has (80% or 60%) transparency.
 
![image](https://user-images.githubusercontent.com/66320309/85064055-385d2400-b1d5-11ea-9e65-33d10b88ba08.png)
I believe you can see the differences between the skin interface and my Action Center interface in this screenshot ;)

**Comment by DoyleElv** [comment]
![image](https://user-images.githubusercontent.com/66320309/85065166-ec12e380-b1d6-11ea-8db5-fdc9855fb21d.png)
This screenshot shows the differences between the skin interface and the side menu of an app's interface, which has blur and 60% opacity.

**Comment by MinhThienDX** [comment]
Look like some folks at Rainmeter have done it.
https://forum.rainmeter.net/viewtopic.php?f=127&t=23106
About integrate it into this repo, sorry we don't have the resource to do so.
Hope you understand.
