### ISSUE TITLE
Issue using win10Widgets GPU

### ISSUE THREAD

**Issue by jlarrieux** [MinhThienDX/win10widgets#38]
I am having an issue where the logs says "!UpdateMeter: [Graph5]not found" 
![image](https://user-images.githubusercontent.com/1837035/101269298-5393ff80-3733-11eb-8745-148cf7259d56.png)

**Comment by jlarrieux** [comment]
Nevermind I figured it out. I had the wrong "win 10  widgets" folder as I needed other files in the @Resources folder like theme.ini and the proper performanceTemplateX4.ini

**Comment by MinhThienDX** [comment]
Glad you found the way 👏
