### ISSUE TITLE
Widgets White

### ISSUE THREAD

**Issue by blackadar** [MinhThienDX/win10widgets#40]
Widget backgrounds by default are solid white when I load any widget. Not sure how to change this, but it also seems like unexpected behavior for first install. Most text is illegible.

**Comment by fireFerry** [comment]
Having the same issue.

**Comment by nartalex** [comment]
The same

![изображение](https://user-images.githubusercontent.com/26258767/115913046-c6024380-a478-11eb-8798-4faa9ba46fd5.png)

**Comment by Kablion** [comment]
I just reinstalled Win10Widgets on my PC and it works fine. 
For us to fix this issue we need additional info.
Did you place the "Win10 Widgets" folder directly into the "C:\Users\USERNAME\Documents\Rainmeter\Skins\" folder?

**Comment by nartalex** [comment]
I've just reinstalled Rainmeter and widgets, everything works fine now
Thanks @Kablion

**Comment by MinhThienDX** [comment]
> 
> 
> I've just reinstalled Rainmeter and widgets, everything works fine now
> Thanks @Kablion

@blackadar @fireFerry Would you kindly reinstalled Rainmeter and widgets?
I will close this, feel free to comment your results.
