### ISSUE TITLE
HWiNFO64 not working with CPU/GPU Temps

### ISSUE THREAD

**Issue by fireFerry** [MinhThienDX/win10widgets#44]
HWiNFO64 version:
![afbeelding](https://user-images.githubusercontent.com/61279925/116197356-f70e9c80-a734-11eb-9f3e-4d395ea7e683.png)
Error:
![afbeelding](https://user-images.githubusercontent.com/61279925/116197448-11e11100-a735-11eb-8887-df82f6732799.png)

I'm only using HWiNFO64, not MSIAfterburner, but the dll won't load.

**Comment by Rameenh** [comment]
Have you tried making sure that HWiNFO is running in the background while you have the CPU and GPU skins open? It's not enough for the program to merely be installed on the system I think.

**Comment by fireFerry** [comment]
Yes, it is running
https://i.imgur.com/bVfKxkL.png

**Comment by ffpp2003** [comment]
Same problem here.
![image](https://user-images.githubusercontent.com/25625404/120733250-2dba9e00-c4bd-11eb-86c5-42e0edf6c78a.png)
i only have HWINFO64 v7.04-4480 installed. Is it nessesary to set up something in hwinfo or edit something for the temps to show up?
![image](https://user-images.githubusercontent.com/25625404/120733713-129c5e00-c4be-11eb-95bc-302318cf1204.png)

**Comment by ffpp2003** [comment]
I was able to fix this problem by installing the HWiNFO rmskin. It includes the missing librarie for HWiNFO meassurments to work properly. Also, i discovered that Shared Memory has to be enabled in HWiNFO settings for the values to be read. After modifying the skin sensor values i got it to work properly on CPU and GPU
[HWiNFO_3.2.0.rmskin.zip](https://github.com/MinhThienDX/win10widgets/files/6598732/HWiNFO_3.2.0.rmskin.zip)
this should be something included in the README.md file for people that are new to the RainMeter world

**Comment by fireFerry** [comment]
Didn't work for me, I enabled shared memory support and can see my GPU temps in the app, but won't work with rainmeter

**Comment by MinhThienDX** [comment]
> 
> 
> Didn't work for me, I enabled shared memory support and can see my GPU temps in the app, but won't work with Rainmeter.
> 
> Edit: I think I got it to work :)

Would you kindly tell me how did you get it to work?

**Comment by MinhThienDX** [comment]
@ffpp2003 I updated README, would you kindly take a look [here](https://github.com/MinhThienDX/win10widgets/blob/master/README.md)?

**Comment by fpp3** [comment]
hahahaha, you didnt need to call me a hero!
It looks good to me!

**Comment by fireFerry** [comment]
> 
> 
> > Didn't work for me, I enabled shared memory support and can see my GPU temps in the app, but won't work with Rainmeter.
> > Edit: I think I got it to work :)
> 
> @fireFerry Would you kindly tell me how did you get it to work?

I just tried it and I think I restarted rainmeter and hwinfo a few times and then it seemed to work
